 apiVersion: extensions/v1beta1
 kind: Deployment
 metadata:
   name: pricev1-deployement
 spec:
   replicas: 1
   selector:
     matchLabels:
       app: pricev1
   template:
     metadata:
       labels:
         app: pricev1
     spec:
       containers:
       - name: pricev1
         image: uk.icr.io/pricev1/pricev1:1.0
         imagePullPolicy: Always
         ports:
         - containerPort: 5000